
[tool.poetry]
name = "python-decorators-utils"
version = "0.1.0"
description = "A collection of useful Python decorators including timing and caching"
authors = ["Udit Anand <getuditanand@gmail.com>"]
readme = "README.md"
packages = ["Decorators"]

[tool.poetry.dependencies]
python = ">=3.11"

[tool.poetry.group.dev.dependencies]
build = "*"
twine = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
