
[project]
name = "python-decorators-utils"
version = "0.1.0"
description = "A collection of useful Python decorators including timing and caching"
authors = [{"name" = "Udit Anand", "email" = "getuditanand@gmail.com"}]
readme = "README.md"
requires-python = ">=3.11"
packages = ["Decorators"]
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
