
[project]
name = "python-decorators-utils"
version = "0.1.0"
description = "A collection of useful Python decorators including timing and caching"
authors = [{"name" = "Your Name", "email" = "you@example.com"}]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
